language: node_js
node_js:
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"
install:
  - npm install -g grunt-cli@0.1.9
  - npm install
  - gem install debugger-linecache -v '1.2.0' --with-ruby-include=$rvm_path/src/ruby-1.9.3-p484/
  - bundle install
notifications:
  email: false
cache:
  bundler: true
  directories:
    - node_modules
