language: node_js
node_js:
  - "0.10"
install:
  - npm install -g grunt-cli@0.1.9
  - npm install
  - bundle install
notifications:
  email: false
cache:
  bundler: true
  directories:
    - node_modules
