language: node_js
node_js:
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"
install:
  - npm install -g grunt-cli@0.1.9
  - npm install
  - bundle install
notifications:
  email: false
